services:
  Symfony\Component\HttpFoundation\Request:
    factory: Symfony\Component\HttpFoundation\Request::createFromGlobals
  TheIconic\Tracking\GoogleAnalytics\Analytics:
    factory: PetrKnapCz\GoogleAnalyticsFactory::create
    arguments:
      - '@Symfony\Component\HttpFoundation\Request'
      - '%google_analytics.tracking_id%'
  Swift_Mailer:
    factory: PetrKnapCz\SwiftMailerFactory::create
    arguments:
      - '%smtp.host%'
      - '%smtp.port%'
      - '%smtp.username%'
      - '%smtp.password%'
      - '%smtp.encryption%'
  PDO:
    class: PDO
    arguments:
      - '%database.dsn%'
      - '%database.username%'
      - '%database.password%'
  PetrKnap\Php\MigrationTool\SqlMigrationTool:
    class: PetrKnap\Php\MigrationTool\SqlMigrationTool
    arguments:
      - '%database.migrations_dir%'
      - '@PDO'
  PetrKnapCz\BackUpService:
    class: PetrKnapCz\BackUpService
    arguments:
      - '%backup.dir%'
      - '%backup.files%'
  PetrKnapCz\BackupWatchdogCache:
    class: Symfony\Component\Cache\Adapter\FilesystemAdapter
    arguments:
      - '%cache.backup_watchdog.namespace%'
      - 1
      - '%cache.dir%'
  PetrKnapCz\BackupWatchdog:
    class: PetrKnapCz\BackupWatchdog
    arguments:
      $cache: '@PetrKnapCz\BackupWatchdogCache'
      $lifeTimes:
        local: 172800
        petrknap.cz: 172800
        prcek: 1209600
  PetrKnapCz\RemoteContentCache:
    class: Symfony\Component\Cache\Adapter\FilesystemAdapter
    arguments:
      - '%cache.remote_content.namespace%'
      - '%cache.remote_content.lifetime%'
      - '%cache.dir%'
  PetrKnapCz\RemoteContentAccessor:
    class: PetrKnapCz\RemoteContentAccessor
    arguments:
      - '@PetrKnapCz\RemoteContentCache'
  PetrKnapCz\RavealContentCache:
    class: Symfony\Component\Cache\Adapter\FilesystemAdapter
    arguments:
      - '%cache.reveal.namespace%'
      - '%cache.reveal.lifetime%'
      - '%cache.dir%'
  PetrKnapCz\RavealAsPages:
    class: PetrKnapCz\RavealAsPages
    arguments:
      - '@PetrKnapCz\RavealContentCache'
  PetrKnapCz\UrlShortenerService:
    class: PetrKnapCz\UrlShortenerService
    arguments:
      - '@PDO'
      - '@PetrKnapCz\RemoteContentAccessor'
